### PR TITLE
Add allowAnyObjectNotation

### PR DESCRIPTION
**Pull request by malinink**
#16
Implementation for Any Object validation support

### CODE REVIEW

**Comment by byjg** [comment]
Great feature! 

Could you add a unit test for this?

**Comment by byjg** [comment]
Hi! I created a unit test for this feature. Could you test and check if your feature is OK?

**Comment by malinink** [comment]
@byjg Please look at my fixes, now it works as expected.

**Comment by byjg** [comment]
Thank you. I'll review with other projects I have and them I'll generate a new version if everything is OK.

**Comment by malinink** [comment]
@byjg Thanks a lot!

**Pull request merged**
