### PR TITLE
Optional HTTP transport for version3

### PR DESCRIPTION
**Pull request by UlrichEckhardt**
As per previous discussion (https://github.com/byjg/php-swagger-test/pull/40), here's the code based on the upcoming major release 3.

### CODE REVIEW

**Comment by UlrichEckhardt** [comment]
Hold on, I just noticed that this breaks PHP 5.6 compatibility. I'll fix that...

**Comment by UlrichEckhardt** [comment]
Okay, the PHPUnit tests pass now. I'm not sure if I can do anything about the others, seems to be a permission/licensing issue.

**Comment by byjg** [comment]
Excellent!!! It is good to merge. If you have an example on how to use the `AbstractRequester` would be interesting have this on README.md after the section `# Using it as Functional Test cases`

**Comment by UlrichEckhardt** [comment]
The way I'm using it is that I forward the request to the routing component of the framework that we're using. For that, I also have to convert the request and response types a bit, since Phalcon 3 uses its own types:
```
class MyAppRequester extends AbstractRequester
{
    /** @var MyAppKernel */
    private $app;

    public function __construct(MyAppKernel $app)
    {
        $this->app = $app;
    }

    /**
     * message exchange implementation required by baseclass
     *
     * This converts the PSR-7 request into the type that Phalcon understands,
     * passes the request to the application instance and converts the respons
     * back to a PSR-7 response.
     *
     * TODO:
     *  - This is untested with payload in the request body or uploaded files,
     *    so there may well be a few cases where this doesn't fully work yet.
     */
    protected function handleRequest(RequestInterface $request)
    {
        // convert request to Phalcon representation
        $phRequest = $request->getRequestTarget();

        // process request
        $phResponse = $this->app->handle($phRequest);

        // convert response to PSR-7 representation
        $headers = $phResponse->getHeaders();
        $status = $phResponse->getStatusCode() ?? 200;
        $content = $phResponse->getContent();
        return new Response(
            $status,
            $headers->toArray(),
            $content
        );
    }
}
```
In other words, it's just a bit of gluecode that anyone can use to tie it into whatever setup they have. Also, and that's another advantage, I can inject a slightly modified kernel that doesn't require the full infrastructure (DBs, certificates, file storage).

**Pull request merged**
