### PR TITLE
Add OpenAPI 3 support

### PR DESCRIPTION
**Pull request by gustavoporcides**
Add basic OpenAPI 3 support. This means that a Swagger specification
that was migrated to OpenAPI 3 should work without issues. The new

### CODE REVIEW

**Comment by byjg** [comment]
Thank you for your PR. I realize you did it backward compatible to Swagger 2.0 which is amazing. 

I will analyse the PR today later and then I'll merge it.

**Comment by byjg** [comment]
I analysed the PR and it is wonderful has a class backward compatible with the old specification and I prefer this way. However we have to take special attention on some details that I will recommend for you:  

**1. Separe Unit Tests from Swagger 2.0 and OpenApi 3.0**

If they are together maybe the test cannot be accurate. For example:

First Scenario:

```php
<?php
$requestParameter = self::swaggerSchema()->getRequestParameters('/v2/store/order', 'post');
$this->assertTrue($requestParameter->match($body));
$requestParameter = self::openApiSchema()->getRequestParameters('/v2/store/order', 'post');
$this->assertTrue($requestParameter->match($body));
```
If the first assert fail does not mean the second will fail also. The problem here is we are trying to test two subject completely different. So, Swagger 2.0 could fail and we do not know if OpenApi 3.0 is working or not. 

Second Scenario:

```php
<?php
/**
 * @expectedException \ByJG\Swagger\Exception\RequiredArgumentNotFound
 * @expectedExceptionMessage The body is required
 */
public function testMatchRequiredRequestBodyEmpty()
{
    $requestParameter = self::swaggerSchema()->getRequestParameters('/v2/store/order', 'post');
    $this->assertTrue($requestParameter->match(null));
    $requestParameter = self::openApiSchema2()->getRequestParameters('/v2/store/order', 'post');
    $this->assertTrue($requestParameter->match(null));
}
```

This test will pass if an exception is raised. Let's analyse this situation. If first assert raise an expected exception the PHPUnit will mark this test as good. However, the second part will NEVER be tested. Another case, if the first assert dont raise any kind of exception and the second part raises, the test will be marked as good, however in both case scenarios we never really have certain if the test is OK and the application could fail. 

Recomendation: Split the tests in two: One for Swagger 2.0 and another for OpenApi 3.0

**2. Create a class for Handle the Swagger 2.0 and another for Handle the OpenApi 3.0**

Example:

```php
<?php
    public function getRequestParameters($path, $method)
    {
        $structure = $this->getPathDefinition($path, $method);

        if($this->getSpecificationVersion() === '3') {
            if (!isset($structure['requestBody'])) {
                return new SwaggerRequestBody($this, "$method $path", []);
            }
            return new SwaggerRequestBody($this, "$method $path", $structure['requestBody']);
        }

        if (!isset($structure[self::SWAGGER_PARAMETERS])) {
            return new SwaggerRequestBody($this, "$method $path", []);
        }
        return new SwaggerRequestBody($this, "$method $path", $structure[self::SWAGGER_PARAMETERS]);
```

This code works great but the readability is not good. We could create two classes here --> One for Swagger and Another for OpenApi implementing some interface and inherited from a base class with the common methods. The specific method will be in the specific proper without the necessity of `if`.

What do you think about this?

**Comment by gustavoporcides** [comment]
Regarding the tests I agree. It makes sense. 

About your second point, I would rather keep the very few ifs we have. I think it would be better to keep them because, as I wrote, they're very few and also because by keeping them in same method anyone who uses the lib wouldn't need to change their code to use the correct method.

**Comment by byjg** [comment]
Great! The second point it is not a problem at all. But the tests is a problem. If you done this tests I'll merge this and prepare to release a new version with this.

**Comment by gustavoporcides** [comment]
Sure. I'll do it on Monday and update the PR.

**Comment by gustavoporcides** [comment]
I've just fixed the tests and updated the PR. Please take a look and see if it is good enough to merge.

Regarding the second point, it really makes sense to go the inheritance way, but I currently don't have the time to do it. I would be happy to do it at a later time (or if someone else does it, that it would be ok too).

**Comment by byjg** [comment]
Yeah, seems much better! Now, I'll do some tests with my legacy applications and then merge it. 

Thank you.

**Comment by gustavoporcides** [comment]
Hi. I see that you merged it to your branch. Any ETA on the merge to master and making a new release?

**Comment by JurisU** [comment]
Referenced parameters not working. Example of schema:
```
openapi: 3.0.0
info:
paths:
    '/tests/{test_id}':
        get:
            parameters:
                -
                    $ref: '#/components/parameters/count'
                -
                    $ref: '#/components/parameters/offset'
            responses:
                '200':
                    description: 'Empty response'
                    content:
                        application/json:
                            schema:
                                description: 'Empty response'
        parameters:
            -
                $ref: '#/components/parameters/test_id'
components:
    parameters:
        count:
            name: count
            in: query
            required: false
            schema:
                type: integer
                default: 10
                maximum: 500
                readOnly: true
        offset:
            name: offset
            in: query
            required: false
            schema:
                type: integer
                default: 0
                readOnly: true
        test_id:
            name: test_id
            in: path
            required: true
            schema:
                type: string
    
```
This is valid OpenAPI v 3.0 schema.

**Comment by byjg** [comment]
@gustavoporcides I leave some weeks in the branch before to merge it and created a release. Fortunately @JurisU catch a bug in this branch before become production. Could you take a look into this?

**Comment by gustavoporcides** [comment]
> Referenced parameters not working. Example of schema:
> 
> ```
> openapi: 3.0.0
> info:
> paths:
>     '/tests/{test_id}':
>         get:
>             parameters:
>                 -
>                     $ref: '#/components/parameters/count'
>                 -
>                     $ref: '#/components/parameters/offset'
>             responses:
>                 '200':
>                     description: 'Empty response'
>                     content:
>                         application/json:
>                             schema:
>                                 description: 'Empty response'
>         parameters:
>             -
>                 $ref: '#/components/parameters/test_id'
> components:
>     parameters:
>         count:
>             name: count
>             in: query
>             required: false
>             schema:
>                 type: integer
>                 default: 10
>                 maximum: 500
>                 readOnly: true
>         offset:
>             name: offset
>             in: query
>             required: false
>             schema:
>                 type: integer
>                 default: 0
>                 readOnly: true
>         test_id:
>             name: test_id
>             in: path
>             required: true
>             schema:
>                 type: string
>     
> ```
> 
> This is valid OpenAPI v 3.0 schema.

1 - does it work on master (using the 2.0 schema, of course)?
2 - what exception does it throw?

I think I haven't changed anything in the parameters part. By the looks of it, I dare to say that it doesn't   support $ref on query/path parameters even on master. Body parameters seem to be OK because they are handled on SwaggerRequestBody class, but I can't really find where the other are handled.

**Comment by byjg** [comment]
I am moving this discussion for the issue #23 . This is an old behavior and I'll take a look on it.

**Pull request merged**
